language: java

services:
  - docker

jdk:
  - openjdk8
  
before_install:
 - chmod +x gradlew
 - chmod +x docker-build-all.sh
 - chmod +x docker-push.sh

before_script:
  - ./gradlew :micronaut-data-jdbc:assemble

script:
  - ./docker-build-all.sh

deploy:
  - ./docker-push.sh
  